; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
framework = arduino
board = esp32doit-devkit-v1
upload_speed = 115200
monitor_speed = 115200
board_build.filesystem = littleFS
board_build.partitions = partitions.csv
lib_deps = 
	gyverlibs/GyverTimer@^3.2
	gyverlibs/GyverBlinker@^1.1.0
	bblanchon/ArduinoJson@^7.0.0
	esphome/ESPAsyncWebServer-esphome
	esphome/ESPAsyncTCP-esphome
	https://github.com/ayushsharma82/ElegantOTA#3.1.6
	robtillaart/ADS1X15@^0.5.1
	bodmer/TFT_eSPI@^2.5.43
	jasonacox/TM1637TinyDisplay@^1.1.0
	adafruit/MAX6675 library@^1.1.2
	adafruit/Adafruit MCP23017 Arduino Library@^2.3.2
	; gyverlibs/GyverEncoder@^4.10
	gyverlibs/EncButton@^3.6.3

build_flags = -DELEGANTOTA_USE_ASYNC_WEBSERVER=1
check_flags = 
	cppcheck: --suppress=*:*.pio\*
