#include <Arduino.h>
#include <ArduinoJson.h>
#include <css.h>
#include <js.h>

const char htmlStart[] PROGMEM = R"rawliteral(
<!DOCTYPE html>
<html lang="ru">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <title>Янтарьбот WiFi</title>
  <style>
)rawliteral";

const char htmlMiddle[] PROGMEM = R"rawliteral(
  </style>
</head>
<body><div class="page"><div id="header-block"><header class="header"><h1 class="title">Янтарьбот WiFi</h1><p class="version">Версия 3.2</p><p class="subtitle">Автоматика для варки янтаря с возможностью изменять параметры по WiFi</p></header></div><section class="process" id="process_block"><div class="process_left_time"><span id="timeLeftHour"></span><span>:</span><span id="timeLeftMins"></span><span>:</span><span id="timeLeftSec"></span><p class="process_subtitle">Времени осталось</p></div><div class="process_past_time"><span>Времени прошло:&nbsp;</span><span id="pastHours"></span><span>&nbsp;:&nbsp;</span><span id="pastMins"></span><span>&nbsp;:&nbsp;</span><span id="pastSec"></span></div><div class="process_diapazons"><span>Диапазон давлений:&nbsp;</span><span id="maxPress"></span><span>-</span><span id="minPress"></span><span>&nbsp;бар</span></div><div class="process_diapazons"><span>Диапазон температур:&nbsp;</span><span id="maxTemp"></span><span>-</span><span id="minTemp"></span><span>&nbsp;град</span></div><div class="process_pressure"><span>Давление в системе:&nbsp;</span><span id="pressure" class="pressure-value"></span><span>&nbsp;бар</span></div><div class="process_pressure"><span>Температура:&nbsp;</span><span id="temperature" class="pressure-value"></span><span>&nbsp;град</span></div></section><div id="middle-block"><div class="button-container"><button class="add-culture-btn" onclick="addCulture()">Добавить программу</button><button class="check-btn" onclick="checkTables()">Проверить</button><button class="factory-reset-btn">Заводские настройки</button><button class="save-btn" onclick="saveData()">Сохранить!</button></div></div><div class="table-container"></div><div id="bottom-block" class="bottom-blk"><button class="check-btn-bottom" onclick="checkTables()">Проверить</button><section class="settings" id="settings"><h2>Настройки</h2><label class="form-switch"><input type="checkbox" id="protectionSwitch"><i></i>Аварийная защита</label><br><p class="timerangetext">Если маслостанция работает не выключаясь установленное количество секунд, программа отжима останавливается. Предназначенно для непредвиденных случаев, например, если забыли перевести рукоятку на маслостанции в рабочее положение или случился серьёзный прорыв шланга РВД.</p><p class="timerangetext">Время срабатывания в секундах:</p><label><input class="timerange" type="range" id="protectionTime" min="5" max="30" value="10" disabled="disabled"><span id="protectionTimeValue">10</span></label><br><br><hr class="hr-simple"><label class="form-switch"><input type="checkbox" id="beeperSwitch"><i></i>Звуковой сигнал</label><p>Один сигнал при включении и при старте; 3 сигнала по окончанию программы</p>
<hr class="hr-simple"><label class="wifilabels">Порог сброса давления (бар):</label><br>
<input maxlength="3" type="number" id="stopPressure" class="wide-input" min="0" max="100" step="1"><br>
<hr class="hr-simple"><h3>Настройка WiFI</h3><p>Введите параметры вашей домашей WiFI сети, тогда вы сможете обращаться к контроллеру с любого другого устройства, подключённого к этой же сети. Для этого нужно будет набрать в браузере адрес, отображённый на 1-м экране при загрузке контроллера.</p><div id="wifiCredentials"><label class="wifilabels">Имя сети (SSID):</label><br><input maxlength="20" type="text" id="ssid" class="wide-input"><br><label class="wifilabels">Пароль:</label><br><input maxlength="20" type="text" id="password" class="wide-input"><br></div><p>Если контроллеру не удастся подключиться домашней сети, то будет создана точка доступа, адреса доступа отобразятся на 1-м экране загрузки контроллера</p><p>После ввода или изменения параметров WiFi нажмите кнопку "Сохранить параметры" и перезагрузите контроллер</p><p>Если нужно вернуть подключение к контроллеру как к точке доступа, просто сотрите поля с названием сети и паролем, нажмите "Сохранить параметры" и перезагрузите контроллер</p><div class="dangerzone"><hr><p class="pressureDiv">Датчик давления</p><p>Внимание! Изменяя эту настройку, вы должны быть точно уверены, что у вас установлен соответствующий датчик давления, иначе корректная работа устройства не гарантируется.</p><select id="pressureDiv" class="pressureselect"><option value="60">60</option><option value="70">70</option><option value="80">80</option><option value="100">100</option></select><span class="mpa">Мпа</span><hr></div><br><button onclick="saveSets()" class="check-btn">Сохранить настройки</button><div class="update-container"><h3 class="upd_title">Обновление прошивки</h3><button class="update-button" onclick='document.location="/update"'>Перейти к обновлению</button></div></section><br><br></div>
<script>
)rawliteral";